### ISSUE TITLE
Para lunes 24 Agosto

### ISSUE THREAD

**Issue by celtre** [celtre/proyectoP#2]
Se entrega:
- Alcance y Rerimientos
- Interfaz Grafica (Plantilla)
- Dudas sobre bases de datos
- Tareas de clase

**Comment by celtre** [comment]
Test problema con laravel

**Comment by enso326** [comment]
revise unas cosas sobre las historias de usuarios, no son tan complejas como parecen. Creo que lo mas dificil de este y de muchos es los limites, alcance o tope de funciones. 
el limite del proyecto debe ser algo consensuado, todos debemos estar presente y de acuerdo con la funciones de la app. propongo un Hangouts‎ o vídeoconferencia en la cual decidamos todos.  
no he podido hacer lo de laravel ya que tengo que formatear el pc pero tengo un monton de cosas difíciles de mover. pero eso lo hago este finde.
lo del cronograma es mas sencillo cuando se tenga todo decidido.
el video que mas me gusto fue https://www.youtube.com/watch?v=PEaqUlwyDS4
desidan la hora y fecha de la Vconferencia

**Comment by celtre** [comment]
Final del issue, el profesor nos revizó la lectura y practicamente naide leyó.

Mayoria de los problemas con laravel solucionados, nuevos objetivos planteados al finalizar la clase.
