### ISSUE TITLE
Entrega 7 de Septiembre

### ISSUE THREAD

**Issue by celtre** [celtre/proyectoP#3]
Se debe tener

```
     1 Autenticacion
     2 Subir y bajar archivos
     3 Modelo de base de datos
     4 Cronograma organizado por semana
```

**Comment by ceciliacastellar** [comment]
Bueno tenemos:
1 La Autenticación 
2 La subida de archivo.
3 Hemos iniciado la base de datos.

Nos falta:
1 Bajada de archivos.
2 Hacer un cronograma por semanas

**Comment by jairoserrano** [comment]
Cada uno de estos items, debe ser un ISSUE en sí.
